/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 blackhole.glb -t -T 
Files: blackhole.glb [13.82MB] > C:\Users\amtsn\OneDrive\Documents\Yr12\CS\itm\Project-Galactic\public\3D\blackhole-transformed.glb [747.2KB] (95%)
Author: rubykamen (https://sketchfab.com/rubykamen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/blackhole-74cbeaeae2174a218fe9455d77902b5c
Title: Blackhole
*/

import * as THREE from 'three'
import {useRef} from 'react'
import {useGLTF, useAnimations, OrbitControls} from '@react-three/drei'
import type {GLTF} from 'three-stdlib'
import {Canvas} from "@react-three/fiber";

type ActionName = 'Take 001'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Blackhole_ring_Blackhole_ring_0: THREE.Mesh
    Blackhole_skin_001_Blackhole_skin_0: THREE.Mesh
    Blackhole_skin_002_Blackhole_core_0: THREE.Mesh
    Blackhole_skin_003_Blackhole_skin_0: THREE.Mesh
    Blackhole_skin_004_Blackhole_core_0: THREE.Mesh
    Blackhole_skin_005_Blackhole_skin_0: THREE.Mesh
    Blackhole_skin_006_Blackhole_skin_inner_0: THREE.Mesh
    Blackhole_skin_007_Blackhole_core_0: THREE.Mesh
    Blackhole_core001_Blackhole_core_0: THREE.Mesh
    Blackhole_skin_008_Blackhole_skin_inner_0: THREE.Mesh
    Blackhole_skin_009_Blackhole_skin_0: THREE.Mesh
    Blackhole_skin_010_Blackhole_skin_0: THREE.Mesh
    Blackhole_skin_011_Blackhole_core_0: THREE.Mesh
    Blackhole_skin_012_Blackhole_skin_inner_0: THREE.Mesh
    Blackhole_skin_013_Blackhole_ring2_0: THREE.Mesh
    Blackhole_core002_Blackhole_ring2_0: THREE.Mesh
    Blackhole_core_Blackhole_core_0: THREE.Mesh
  }
  materials: {
    Blackhole_ring: THREE.MeshStandardMaterial
    Blackhole_skin: THREE.MeshStandardMaterial
    Blackhole_core: THREE.MeshStandardMaterial
    Blackhole_skin_inner: THREE.MeshStandardMaterial
    Blackhole_ring2: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('./3D/blackhole-transformed.glb') as GLTFResult
  useAnimations(animations, group)
  return (
    <group
        position={[0, 0.5, 0]}
        ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" scale={0.016}>
          <group name="Blackhole_ring" rotation={[-Math.PI / 2, 0, 0]}>
            <mesh name="Blackhole_ring_Blackhole_ring_0" geometry={nodes.Blackhole_ring_Blackhole_ring_0.geometry} material={materials.Blackhole_ring} />
          </group>
          <group name="Blackhole_skin_001" rotation={[-Math.PI / 2, 0, 0]} scale={0.959}>
            <mesh name="Blackhole_skin_001_Blackhole_skin_0" geometry={nodes.Blackhole_skin_001_Blackhole_skin_0.geometry} material={materials.Blackhole_skin} />
          </group>
          <group name="Blackhole_skin_002" rotation={[-Math.PI / 2, 0, 0]} scale={0.957}>
            <mesh name="Blackhole_skin_002_Blackhole_core_0" geometry={nodes.Blackhole_skin_002_Blackhole_core_0.geometry} material={materials.Blackhole_core} />
          </group>
          <group name="Blackhole_skin_003" rotation={[-Math.PI / 2, 0, 0]} scale={0.91}>
            <mesh name="Blackhole_skin_003_Blackhole_skin_0" geometry={nodes.Blackhole_skin_003_Blackhole_skin_0.geometry} material={materials.Blackhole_skin} />
          </group>
          <group name="Blackhole_skin_004" rotation={[-Math.PI / 2, 0, 0]} scale={0.908}>
            <mesh name="Blackhole_skin_004_Blackhole_core_0" geometry={nodes.Blackhole_skin_004_Blackhole_core_0.geometry} material={materials.Blackhole_core} />
          </group>
          <group name="Blackhole_skin_005" rotation={[-Math.PI / 2, 0, 0.96]} scale={0.9}>
            <mesh name="Blackhole_skin_005_Blackhole_skin_0" geometry={nodes.Blackhole_skin_005_Blackhole_skin_0.geometry} material={materials.Blackhole_skin} />
          </group>
          <group name="Blackhole_skin_006" rotation={[-Math.PI / 2, 0, -2.007]} scale={0.864}>
            <mesh name="Blackhole_skin_006_Blackhole_skin_inner_0" geometry={nodes.Blackhole_skin_006_Blackhole_skin_inner_0.geometry} material={materials.Blackhole_skin_inner} />
          </group>
          <group name="Blackhole_skin_007" rotation={[-Math.PI / 2, 0, -2.007]} scale={0.866}>
            <mesh name="Blackhole_skin_007_Blackhole_core_0" geometry={nodes.Blackhole_skin_007_Blackhole_core_0.geometry} material={materials.Blackhole_core} />
          </group>
          <group name="Blackhole_core001" rotation={[-Math.PI / 2, 0, 0]}>
            <mesh name="Blackhole_core001_Blackhole_core_0" geometry={nodes.Blackhole_core001_Blackhole_core_0.geometry} material={materials.Blackhole_core} />
          </group>
          <group name="Blackhole_skin_008" rotation={[-Math.PI / 2, 0, 0.087]} scale={0.845}>
            <mesh name="Blackhole_skin_008_Blackhole_skin_inner_0" geometry={nodes.Blackhole_skin_008_Blackhole_skin_inner_0.geometry} material={materials.Blackhole_skin_inner} />
          </group>
          <group name="Blackhole_skin_009" rotation={[-Math.PI / 2, 0, -0.611]} scale={0.887}>
            <mesh name="Blackhole_skin_009_Blackhole_skin_0" geometry={nodes.Blackhole_skin_009_Blackhole_skin_0.geometry} material={materials.Blackhole_skin} />
          </group>
          <group name="Blackhole_skin_010" rotation={[-Math.PI / 2, 0, -2.531]} scale={0.929}>
            <mesh name="Blackhole_skin_010_Blackhole_skin_0" geometry={nodes.Blackhole_skin_010_Blackhole_skin_0.geometry} material={materials.Blackhole_skin} />
          </group>
          <group name="Blackhole_skin_011" rotation={[-Math.PI / 2, 0, -2.531]} scale={0.928}>
            <mesh name="Blackhole_skin_011_Blackhole_core_0" geometry={nodes.Blackhole_skin_011_Blackhole_core_0.geometry} material={materials.Blackhole_core} />
          </group>
          <group name="Blackhole_skin_012" rotation={[-Math.PI / 2, 0, 2.094]} scale={0.856}>
            <mesh name="Blackhole_skin_012_Blackhole_skin_inner_0" geometry={nodes.Blackhole_skin_012_Blackhole_skin_inner_0.geometry} material={materials.Blackhole_skin_inner} />
          </group>
          <group name="Blackhole_skin_013" rotation={[-Math.PI / 2, 0, -2.967]} scale={0.835}>
            <mesh name="Blackhole_skin_013_Blackhole_ring2_0" geometry={nodes.Blackhole_skin_013_Blackhole_ring2_0.geometry} material={materials.Blackhole_ring2} />
          </group>
          <group name="Blackhole_core002" rotation={[-Math.PI / 2, 0, 0]} scale={0.928}>
            <mesh name="Blackhole_core002_Blackhole_ring2_0" geometry={nodes.Blackhole_core002_Blackhole_ring2_0.geometry} material={materials.Blackhole_ring2} />
          </group>
        </group>
        <mesh name="Blackhole_core_Blackhole_core_0" geometry={nodes.Blackhole_core_Blackhole_core_0.geometry} material={materials.Blackhole_core} rotation={[-Math.PI / 2, 0, 0]} scale={0.015} />
      </group>
    </group>
  )
}

export default function Blackhole() {
  return (
      <Canvas
          camera={{ position: [0, 1, 4], fov: 105 }}
          style={{ width: "100%", height: "100%" }}
      >
        {/* Lights */}
        <ambientLight intensity={0.5} />
        <directionalLight position={[3, 3, 3]} intensity={1.2} />

        {/* Model */}
        <Model />

        {/* Controls */}
        <OrbitControls
            autoRotate
            autoRotateSpeed={3}
            enableZoom={true}
            enablePan={false}
            rotateSpeed={1}
        />
      </Canvas>
  )
}
useGLTF.preload('./3D/blackhole-transformed.glb')
