/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 star.glb -t -T 
Files: star.glb [50.06MB] > C:\Users\amtsn\OneDrive\Documents\Yr12\CS\itm\Project-Galactic\public\3D\star-transformed.glb [1.42MB] (97%)
*/

import * as THREE from 'three'
import {OrbitControls, useGLTF} from '@react-three/drei'
import type {GLTF} from 'three-stdlib';
import {Canvas} from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    Sun_LOD0__0: THREE.Mesh
  }
  materials: {
    ['Scene_-_Root']: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./3D/star-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sun_LOD0__0.geometry} material={materials['Scene_-_Root']} position={[0, 4 , 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.116} />
    </group>
  )
}

useGLTF.preload('./3D/star-transformed.glb')

export default function Star() {
  return (
      <Canvas
          camera={{ position: [0, 0, 7], fov: 80 }}
          style={{ width: "100%", height: "100%" }}
      >
        {/* Lights */}
        <ambientLight intensity={0.5} />
        <directionalLight position={[3, 3, 3]} intensity={1.2} />

        {/* Model */}
        <Model />

        {/* Controls */}
        <OrbitControls
            autoRotate
            autoRotateSpeed={3}
            enableZoom={true}
            enablePan={false}
            rotateSpeed={1}
        />
      </Canvas>
  )
}